import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import * as FileSystem from 'expo-file-system/legacy'

const PDF_DIR = FileSystem.documentDirectory + 'letters/'
const PAGE_WIDTH = 612   // US Letter
const PAGE_HEIGHT = 792
const MARGIN = 72        // 1 inch
const LINE_HEIGHT = 18
const BODY_SIZE = 11
const HEADER_SIZE = 13

// ─── Public API ───────────────────────────────────────────────────────────────

export async function generateLetterPDF(
  content: string,
  filename: string
): Promise<string> {
  await ensureDir()
  const pdfBytes = await buildPDF(content)
  const path = PDF_DIR + filename + '.pdf'
  await FileSystem.writeAsStringAsync(path, uint8ToBase64(pdfBytes), {
    encoding: FileSystem.EncodingType.Base64,
  })
  return path
}

// ─── PDF Construction ─────────────────────────────────────────────────────────

async function buildPDF(content: string): Promise<Uint8Array> {
  const doc = await PDFDocument.create()
  const regularFont = await doc.embedFont(StandardFonts.Helvetica)
  const boldFont = await doc.embedFont(StandardFonts.HelveticaBold)

  // Header: app watermark
  const page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT])
  let y = PAGE_HEIGHT - MARGIN

  // Subtle header bar
  page.drawRectangle({
    x: 0, y: PAGE_HEIGHT - 36,
    width: PAGE_WIDTH, height: 36,
    color: rgb(0.05, 0.05, 0.05),
  })
  page.drawText('Generated by AdvocateAI — Free, Private, Offline', {
    x: MARGIN, y: PAGE_HEIGHT - 24,
    size: 8,
    font: regularFont,
    color: rgb(0.6, 0.6, 0.6),
  })

  y -= 12 // gap below header

  // Letter body — wrap each paragraph independently
  const paragraphs = content.split(/\n{2,}/)
  for (const para of paragraphs) {
    const lines = wrapText(para.replace(/\n/g, ' '), regularFont, BODY_SIZE, PAGE_WIDTH - MARGIN * 2)

    // Detect headings: short lines in all-caps or ending with ':'
    const isHeading = lines.length === 1 && (para === para.toUpperCase() || para.endsWith(':'))
    const font = isHeading ? boldFont : regularFont
    const size = isHeading ? HEADER_SIZE : BODY_SIZE

    for (const line of lines) {
      if (y < MARGIN + LINE_HEIGHT) {
        // Overflow to new page
        const newPage = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT])
        y = PAGE_HEIGHT - MARGIN
        drawPageNumber(newPage, doc.getPageCount(), regularFont)
      }

      page.drawText(line, {
        x: MARGIN,
        y,
        size,
        font,
        color: rgb(0.05, 0.05, 0.05),
      })
      y -= LINE_HEIGHT
    }

    y -= LINE_HEIGHT * 0.6 // paragraph spacing
  }

  drawPageNumber(page, 1, regularFont)
  return doc.save()
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function wrapText(
  text: string,
  font: Awaited<ReturnType<PDFDocument['embedFont']>>,
  size: number,
  maxWidth: number
): string[] {
  const words = text.split(' ')
  const lines: string[] = []
  let current = ''

  for (const word of words) {
    const test = current ? `${current} ${word}` : word
    if (font.widthOfTextAtSize(test, size) <= maxWidth) {
      current = test
    } else {
      if (current) lines.push(current)
      current = word
    }
  }
  if (current) lines.push(current)
  return lines
}

function drawPageNumber(
  page: ReturnType<PDFDocument['addPage']>,
  num: number,
  font: Awaited<ReturnType<PDFDocument['embedFont']>>
): void {
  page.drawText(`Page ${num}`, {
    x: PAGE_WIDTH / 2 - 20,
    y: MARGIN / 2,
    size: 9,
    font,
    color: rgb(0.5, 0.5, 0.5),
  })
}

async function ensureDir(): Promise<void> {
  const info = await FileSystem.getInfoAsync(PDF_DIR)
  if (!info.exists) await FileSystem.makeDirectoryAsync(PDF_DIR, { intermediates: true })
}

function uint8ToBase64(bytes: Uint8Array): string {
  let binary = ''
  const len = bytes.byteLength
  for (let i = 0; i < len; i++) binary += String.fromCharCode(bytes[i])
  return btoa(binary)
}
