export const PRIVACY_VERSION = '1.0'
export const PRIVACY_DATE = 'August 2025'

export const PRIVACY_POLICY = `ADVOCATEAI — PRIVACY POLICY
Last Updated: ${PRIVACY_DATE}
Version ${PRIVACY_VERSION}

Your privacy is the foundation of AdvocateAI. This policy explains what information the application handles, where it stays, and your complete control over it.

────────────────────────────────────────
1. THE CORE PROMISE: YOUR DATA NEVER LEAVES YOUR DEVICE
────────────────────────────────────────

AdvocateAI is designed to work 100% offline. When you scan a document or receive an AI analysis:

• No document images, text, or analysis results are ever sent to any server.
• No AI processing happens in the cloud — the AI model runs entirely on your device.
• No account is required. We do not know who you are.
• No analytics, crash reports, or usage data are transmitted.
• No advertising networks or tracking SDKs are included in this application.

The only time your device contacts the internet through this application is if you choose to download the AI model from the Settings screen. That download is of a public AI model file — no personal data is sent.

────────────────────────────────────────
2. WHAT INFORMATION IS STORED ON YOUR DEVICE
────────────────────────────────────────

The following data is stored locally on your device only:

a) DOCUMENT TEXT: The text extracted from documents you scan or import, stored in an encrypted local database on your device.

b) AI ANALYSIS RESULTS: Summaries, findings, and recommended actions generated by the local AI, stored alongside your document records.

c) GENERATED LETTERS: Any letters, scripts, or forms drafted by the AI, stored locally.

d) APP PREFERENCES: Your settings (such as accepted terms version), stored locally.

All document content is protected using AES-256-GCM encryption — the same standard used by banks and governments. The encryption key is derived from your device and never transmitted anywhere.

────────────────────────────────────────
3. SENSITIVE DOCUMENT CONTENT
────────────────────────────────────────

We understand that documents you scan may contain highly sensitive information — medical records, financial details, legal notices, or personal identification. Because all processing occurs entirely on your device:

• No human at AdvocateAI or any other organization can see your documents.
• No automated system outside your device processes your documents.
• Even if you uninstall the application, no copy of your data exists elsewhere.

────────────────────────────────────────
4. DEVICE PERMISSIONS
────────────────────────────────────────

AdvocateAI requests the following device permissions:

CAMERA: To scan physical documents. Photos are processed on-device and never transmitted. Camera access is only active when you are actively scanning.

PHOTO LIBRARY / STORAGE: To import document images or PDFs from your files. Selected files are read on-device only.

MICROPHONE: To allow voice input. Audio is processed on-device by the local speech recognition model and never transmitted.

NOTIFICATIONS: To send deadline reminders you have explicitly requested. Notifications are generated locally and contain no document content.

You may revoke any permission at any time through your device's Settings app. Revoking a permission will disable the associated feature but will not affect stored data.

────────────────────────────────────────
5. NO THIRD-PARTY DATA SHARING
────────────────────────────────────────

We do not sell, share, rent, or disclose your information to any third party — ever. There are no advertisers, data brokers, or analytics partners with access to your data, because no data ever leaves your device.

────────────────────────────────────────
6. CHILDREN'S PRIVACY (COPPA)
────────────────────────────────────────

AdvocateAI is not directed at children under 13 years of age. We do not knowingly collect personal information from children under 13. If you are under 13, do not use this application. Because no data is transmitted from the device, we do not have a mechanism to collect children's data even inadvertently.

────────────────────────────────────────
7. YOUR RIGHTS AND CONTROLS
────────────────────────────────────────

You have complete control over all data stored by AdvocateAI:

• DELETE INDIVIDUAL DOCUMENTS: Tap the delete icon on any document to permanently remove it, including all associated letters and AI analyses.
• DELETE ALL DATA: Uninstalling the application from your device removes all stored data permanently.
• EXPORT YOUR DATA: You may export a case bundle (PDF) of any document and its associated materials to share with a trusted party such as a lawyer or advocate.

Because we hold no data on any server, there is no account to close, no data request to submit, and no remote deletion needed — your device is the only place your data exists.

────────────────────────────────────────
8. DATA SECURITY
────────────────────────────────────────

We take security seriously, especially given the sensitive nature of the documents our users work with:

• Document text and AI results are encrypted at rest using AES-256-GCM.
• The application automatically returns to the home screen after 15 minutes in the background, reducing exposure on shared or unlocked devices.
• No network endpoints exist that could be attacked to access your data.

Despite these protections, no security measure is perfect. If your physical device is compromised by malware or an unauthorized person with access to an unlocked device, your locally stored data could be at risk. We recommend using your device's built-in lock screen protection.

────────────────────────────────────────
9. CHANGES TO THIS PRIVACY POLICY
────────────────────────────────────────

If we make material changes to this Privacy Policy, the updated policy will be presented within the application and will require your renewed acknowledgment. We will never make changes that result in your data being transmitted to a server without your explicit consent.

────────────────────────────────────────
10. CONTACT
────────────────────────────────────────

If you have questions or concerns about this Privacy Policy, please contact the developer through the application's support channel.

We believe privacy is a right, not a feature — especially for people navigating difficult situations. AdvocateAI is built on that belief.`
